### ISSUE TITLE
Doesn't work on current OpenWRT version 

### ISSUE THREAD

**Issue by romanad** [DavBfr/luci-app-netmap#3]
Unable to run on current version (OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.119.80898-65ef406)

/usr/lib/lua/luci/template.lua:97: Failed to execute template 'map/index'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/map/index.htm"]:4: module 'luci.tools.status' not found:
	no field package.preload['luci.tools.status']
	no file './luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status/init.lua'
	no file '/usr/lib/lua/luci/tools/status.lua'
	no file '/usr/lib/lua/luci/tools/status/init.lua'
	no file './luci/tools/status.so'
	no file '/usr/lib/lua/luci/tools/status.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	[string "/usr/lib/lua/luci/view/map/index.htm"]:4: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:1053: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>

**Comment by DavBfr** [comment]
Yes, that's old and not maintained

**Comment by romanad** [comment]
It's sad, the idea is great and there's no alternatives available.
